### ISSUE TITLE
As a user I want to be able to use foreign keys

### ISSUE THREAD

**Issue by mdevn001** [CS180-spring/cs180-23-ganto#38]

**Comment by PhoenixWinter542** [comment]
##Story Points

8

**Comment by PhoenixWinter542** [comment]
## Test Cases

Add Tables
	cout << "\tKeyIsForeign:\t\t";
	if(true == t.apiAddTable("Foreign", {{"name", 0}, {"birthPlace", 0}}, {}, {make_tuple("People", "name")}))
		cout << "Success" << endl;
	else
		cout << "Failed" << endl;

Delete Tables
	cout << "\tTableUsedAsForeignKey:\t";
	if(false == t.apiRemoveTable("DeleteTable"))
		cout << "Success" << endl;
	else
		cout << "Failed" << endl;


	cout << "\tTableWithForeignKey\t";
	if(true == t.apiRemoveTable("ForeignTable") && true == t.apiReadTable("ForeignTable", {}).empty())
		cout << "Success" << endl;
	else
		cout << "Failed" << endl;

	cout << "\tForeignTableRemoved:\t";
	if(true == t.apiRemoveTable("DeleteTable"))
		cout << "Success" << endl;
	else
		cout << "Failed" << endl;
